#!/bin/bash
# this is a wrapper around the python in the venv that
# running this instead of python makes sure you can import from sage
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
source ${SCRIPT_DIR}/bash_sage_init.sh
${SCRIPT_DIR}/../venv/bin/python3 "$@"
