name: Run testsuite using pytest

on: [ workflow_dispatch, pull_request ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: mderickx/sagemath:9.4
      options: --user root

    steps:
      - name: Install git and make
        run: |
          sudo apt-get update
          sudo apt-get install git make -y
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          make pip-install-dev
      - name: make vulture
        run: |
          make vulture
      - name: make test
        run: |
          make test
